In [137]:
import keras
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.model_selection import train_test_split
from keras.optimizers import SGD


In [177]:
data = pd.read_csv('criminal_train.csv')
y_train = data['Criminal']

input_ab = pd.read_csv('input_ab.csv')
input_ab = input_ab['Criminal']

input_gb = pd.read_csv('input_gb.csv')
input_gb = input_gb['Criminal']

input_knn = pd.read_csv('input_knn.csv')
input_knn = input_knn['Criminal']

input_rf = pd.read_csv('input_rf.csv')
input_rf = input_rf['Criminal']

input_lr = pd.read_csv('input_rf.csv')
input_lr = input_lr['Criminal']

input_svm = pd.read_csv('input_svm.csv')
input_svm = input_svm['Criminal']

In [178]:
# training data
i = 0
X_train = []
# rows = 45717
while i <=45717:
    p = []
    p.append(input_ab[i])
    p.append(input_gb[i])
    p.append(input_knn[i])
    p.append(input_rf[i])
    p.append(input_lr[i])
    p.append(input_svm[i])
    X_train.append(p)
    i = i +1
X_train = np.asarray(X_train)
print(X_train)

[[0 0 0 0 0 0]
 [0 0 1 1 1 0]
 [0 0 0 0 0 0]
 ..., 
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [161]:
model = Sequential()
model.add(Dense(2, input_shape=(4,)))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('softmax'))

In [162]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_43 (Dense)             (None, 2)                 10        
_________________________________________________________________
activation_43 (Activation)   (None, 2)                 0         
_________________________________________________________________
dense_44 (Dense)             (None, 1)                 3         
_________________________________________________________________
activation_44 (Activation)   (None, 1)                 0         
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [163]:
sgd = SGD(lr=0.0001, decay=1e-6, momentum=0.9)
model.compile(loss='binary_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

In [171]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
model =LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=.3)

In [179]:
#X_train,X_test, y_train, y_test = train_test_split(X_train,y_train,test_size = .2)
model.fit(X_train, y_train)
one = model.score(X_train, y_train)
#two = model.score(X_test, y_test)
print('training accuracy: ', one)
#print('testing accuracy: ',two)

training accuracy:  0.999912507109


In [180]:
output_ab = pd.read_csv('output_ab.csv')
output_ab = output_ab['Criminal']

output_gb = pd.read_csv('output_gb.csv')
output_gb = output_gb['Criminal']

output_knn = pd.read_csv('output_knn.csv')
output_knn = output_knn['Criminal']

output_rf = pd.read_csv('output_rf.csv')
output_rf = output_rf['Criminal']

output_lr = pd.read_csv('output_rf.csv')
output_lr = output_lr['Criminal']

output_svm = pd.read_csv('output_svm.csv')
output_svm= output_svm['Criminal']

In [181]:
#testing data
i = 0
X_test = []
# rows = 11429
while i <=11429:
    p = []
    p.append(output_ab[i])
    p.append(output_gb[i])
    p.append(output_knn[i])
    p.append(output_rf[i])
    p.append(output_lr[i])
    p.append(output_svm[i])
    X_test.append(p)
    i = i +1
X_test = np.asarray(X_test)

In [182]:
df = pd.read_csv('criminal_test.csv')
predicted = model.predict(X_test)
frame = pd.DataFrame()
frame['PERID'] = df['PERID']
frame['Criminal'] = predicted
frame.to_csv('output.csv', index = False)
